name: Scan
on: [push, pull_request]
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: docker build -t trivy-ci-test:1.2.3
    - name: Scan
      uses: docker://aquasec/trivy
      with:
        args: --severity CRITICAL --no-progress trivy-ci-test:1.2.3
